[workspace]
members = [
    "armstrong-numbers",
    "beer-song",
    "book-store",
    "circular-buffer",
    "clock",
    "difference-of-squares",
    "dot-dsl",
    "etl",
    "gigasecond",
    "grains",
    "hello-world",
    "leap",
    "macros",
    "nth-prime",
    "paasio",
    "poker",
    "prime-factors",
    "proverb",
    "raindrops",
    "react",
    "reverse-string",
    "sum-of-multiples",
    "xorcism",
]
